name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    env:
      MONGO_URI: mongodb://localhost:27017/navigator
      MONGO_DB: navigator
      SERVER_PORT: 8080

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot backend
        run: mvn clean install
        working-directory: Navigator

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and build frontend
        run: npm install && npm run build
        working-directory: navapp-frontend

      # 🔐 Docker Login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 🐳 Build and Push Backend Docker Image
      - name: Build backend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/navigator-backend:latest .
        working-directory: Navigator

      - name: Push backend Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/navigator-backend:latest

      # 🐳 Build and Push Frontend Docker Image
      - name: Build frontend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/navigator-frontend:latest .
        working-directory: navapp-frontend

      - name: Push frontend Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/navigator-frontend:latest